# ----
# Site

title: Flexible
description: Jekyll template for API documentation.
url: https://example.com
google_analytics_key:
permalink: pretty

# -----
# Build

timezone: Etc/UTC

collections:
  documentation:
    title: Getting Started
    position: 1
  api:
    title: APIs
    position: 2
  software:
    title: GET Software 
    position: 3
  hardware:
    title: GET Hardware
    position: 4
  manufacturer:
    title: GET Manufacturer
    position: 5
  cpu:
    title: GET CPU 
    position: 6
  cve:
    title: GET CVE 
    position: 7
  softwarelicense:
    title: GET Software License 
    position: 8
  hardwarelicense:
    title: GET Hardware License 
    position: 9
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENSE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      type: "documentation"
    values:
      _hide_content: true
  -
    scope:
      type: "api"
    values:
      _hide_content: true
  -
    scope:
      type: "software"
    values:
      _hide_content: true
  -
    scope:
      type: "hardware"
    values:
      _hide_content: true
  -
    scope:
      type: "manufacturer"
    values:
      _hide_content: true
  -
    scope:
      type: "CPU"
    values:
      _hide_content: true
  -
    scope:
      type: "CVE"
    values:
      _hide_content: true 
  -
    scope:
      type: "software license"
    values:
      _hide_content: true 
  -
    scope:
      type: "hardware license"
    values:
      _hide_content: true                      


# -----------
# CloudCannon

types:
  - get
  - put
  - delete
  - post

languages:
  bash: Bash
  c: C
  css: CSS
  html: HTML
  java: Java
  javascript: JavaScript
  json: JSON
  php: PHP
  python: Python
  ruby: Ruby

_options:
  content_markdown:
    format: p h1 h2 h3 h4 h5 h6
    bold: true
    italic: true
    link: true
    bulletedlist: true
    numberedlist: true
    images: /images/
    table: true
    styles: /css/editor.css
