# ----
# Site

title: FLEXY
description: Jekyll template for API documentation.
url: https://example.com
google_analytics_key:
permalink: pretty

# -----
# Build

timezone: Etc/UTC

collections:
  documentation:
    title: Documentation
    position: 1
  api:
    title: APIs
    position: 2
  software:
    title: Software
    position: 3
  hardware:
    title: Hardware
    position: 4
   cpu:
    title: CPU 
    position: 5
  cve:
    title: CVE 
    position: 6
  softwarelicense:
    title: Software License 
    position: 8
  hardwarelicense:
    title: Hardware License 
    position: 9
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENSE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      type: "documentation"
    values:
      _hide_content: true
  -
    scope:
      type: "api"
    values:
      _hide_content: true
       -
    scope:
      type: "software"
    values:
      _hide_content: true
  -
    scope:
      type: "hardware"
    values:
      _hide_content: true
      scope:
      type: "cpu"
    values:
      _hide_content: true
  -
    scope:
      type: "cve"
    values:
      _hide_content: true
      scope:
      type: "softwarelicense"
    values:
      _hide_content: true
  -
    scope:
      type: "hardwarelicense"
    values:
      _hide_content: true

# -----------
# CloudCannon

types:
  - get
  - put
  - delete
  - post

languages:
  bash: Bash
  c: C
  css: CSS
  html: HTML
  java: Java
  javascript: JavaScript
  json: JSON
  php: PHP
  python: Python
  ruby: Ruby

_options:
  content_markdown:
    format: p h4 h5 h6
    bold: true
    italic: true
    link: true
    bulletedlist: true
    numberedlist: true
    image: true
    table: true
    styles: /css/editor.css