# ----
# Site

title: Flexible
description: Jekyll template for API documentation.
url: https://example.com
google_analytics_key:
permalink: pretty

# -----
# Build

timezone: Etc/UTC

collections:
  documentation:
    title: Getting Started
    position: 1
  api:
    title: APIs
    position: 2
  Software:
    title: Software GET
    position: 3
  Hardware:
    title: Hardware GET
    position: 4
  Manufacturer:
    title: Manufacturer GET
    position: 5
  CPU:
    title: CPU GET
    position: 6
  CPE:
    title: CPE GET
    position: 7
  Software License:
    title: Software License GET
    position: 8
  Hardware License:
    title: Hardware License GET
    position: 9
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENSE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      type: "documentation"
    values:
      _hide_content: true
  -
    scope:
      type: "api"
    values:
      _hide_content: true
  -
    scope:
      type: "software"
    values:
      _hide_content: true
  -
    scope:
      type: "hardware"
    values:
      _hide_content: true
  -
    scope:
      type: "manufacturer"
    values:
      _hide_content: true
  -
    scope:
      type: "CPU"
    values:
      _hide_content: true
  -
    scope:
      type: "CVE"
    values:
      _hide_content: true 
  -
    scope:
      type: "software license"
    values:
      _hide_content: true 
  -
    scope:
      type: "hardware license"
    values:
      _hide_content: true                      


# -----------
# CloudCannon

types:
  - get
  - put
  - delete
  - post

languages:
  bash: Bash
  c: C
  css: CSS
  html: HTML
  java: Java
  javascript: JavaScript
  json: JSON
  php: PHP
  python: Python
  ruby: Ruby

_options:
  content_markdown:
    format: p h4 h5 h6
    bold: true
    italic: true
    link: true
    bulletedlist: true
    numberedlist: true
    image: true
    table: true
    styles: /css/editor.css
